Add HHBtag_v2 model
hh-italian-group/HHbtag pull request #2
Opened 2023-12-22 13:26 UTC by elviramartinv

This Pull Request is made to check the new HHBtag v2 model and setup  while continuing in parallel with stability studies

2023-12-27 16:04 UTC, kandrosov requested changes
There should be no changes to v1

2023-12-28 20:16 UTC, elviramartinv commented
Now there are no changes to v1

2023-12-28 20:18 UTC, kandrosov commented
thanks! Please also:
- add tests in `bin/hhBtagTest.cc` for v2 (keeping v1 as well)
- update documentation in README.md

2024-01-10 09:55 UTC, elviramartinv commented
README and bin/hhBtagTest.cc are already updated, please let me know if anything else is missing

2024-01-13 20:34 UTC, kandrosov requested changes

2024-01-13 20:34 UTC, kandrosov commented on README.md
> +cd CMSSW_13_0_0_pre1/src
```suggestion
cmsrel CMSSW_12_4_10 # or above
cd CMSSW_12_4_10/src
```

2024-01-13 20:34 UTC, kandrosov commented on bin/hhBtagTest.cc
> +    std:string version = "v1" // model version "v1" or "v2"
- take the model version from the command line so that one can test both
- as it is now, the code doesn't compile

2024-01-17 10:21 UTC, kandrosov approved these changes

2024-01-17 10:29 UTC, kandrosov commented
Thank you @elviramartinv. All looks good. However, I will wait before merging: if training for the whole Run 2 arrives before the new skim iteration, I would prefer to merge it directly. Otherwise, I'll merge this version as v2 and then merge the full Run 2 training as v3.

2024-01-26 12:50 UTC, merged